// Code generated by raindrop build, DO NOT EDIT.
import { ActorNamespace, Ai, Annotation, App, Bucket, KvCache, Logger, MRNObject, ServiceStub, SmartBucket, SmartMemory, SqlDatabase, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  AMAZON_API_KEY: string;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  APP_DB: SqlDatabase;
  AUDIO_UPLOADS: Bucket;
  CROMA_API_KEY: string;
  ELEVENLABS_API_KEY: string;
  ELEVENLABS_VOICE_ID: string;
  FLIPKART_API_KEY: string;
  GEMINI_API_KEY: string;
  GEMINI_MODEL: string;
  GEMINI_VISION_MODEL: string;
  GOOGLE_SEARCH_API_KEY: string;
  GOOGLE_SEARCH_ENGINE_ID: string;
  logger: Logger;
  mem: KvCache;
  OPENAI_API_KEY: string;
  PRODUCT_CACHE: KvCache;
  PRODUCT_SEARCH_ACTOR: ActorNamespace<import('../product-search-actor/index.js').ProductSearchActor>;
  PRODUCTS_KB: SmartBucket;
  SESSION_CACHE: KvCache;
  SHOPPING_API: ServiceStub<import('../shopping-api/index.js').default>;
  tracer: Tracer;
  USER_MEMORY: SmartMemory;
  USER_PREFERENCES_ACTOR: ActorNamespace<import('../user-preferences-actor/index.js').UserPreferencesActor>;
  VOICE_PROCESSOR: ActorNamespace<import('./index.js').VoiceProcessor>;
}
